### ISSUE TITLE
关于steps.sh方法

### ISSUE THREAD

**Issue by monlor** [daluobai-devops/jenkins-shared-library#2]
我看项目中很多地方都可以直接用steps.sh来执行shell脚本，但我没找到这个方法定义的地方，大佬可以解答一下么？

**Comment by wuzhaozhongguo** [comment]
> 我看项目中很多地方都可以直接用steps.sh来执行shell脚本，但我没找到这个方法定义的地方，大佬可以解答一下么？

sh这个是jenkins pipeline内置的对象，具体可以参考https://www.jenkins.io/doc/book/pipeline/syntax/
，也可以在job配置里的步骤生成里找到。
steps是pipeline对象，通过this获取到的，可以参考vars下面的代码，ps:def stepsBuildMaven = new StepsBuildMaven(this)

**Comment by monlor** [comment]
谢谢大佬 我后来看懂了，就是执行sh命令😂
